In [2]:
import numpy as np
python_list=[10,20,30,40,50]
numpy_array=np.array(python_list)
print("Numpy Array",numpy_array)

Numpy Array [10 20 30 40 50]


In [4]:
matrix=np.array([[7,8,9],[10,11,12]])
print("\n2D Array (Matrix):\n",matrix)


2D Array (Matrix):
 [[ 7  8  9]
 [10 11 12]]


In [5]:
array=np.array([6,7,8,9,10])

array_sum=array+3

array_square=array**2
print("\nArray after adding 3:",array_sum)
print("\nArray after squaring:",array_square)



Array after adding 3: [ 9 10 11 12 13]

Array after squaring: [ 36  49  64  81 100]


In [6]:
array1=np.array([1,3,5,7,9])
array2=np.array([2,4,6,8,10])

elementwise_sum =array1+array2
print("\nElement wise sum :",elementwise_sum)


Element wise sum : [ 3  7 11 15 19]


In [7]:
array=np.array([15,25,35,45,55])
mean_value=np.mean(array)
max_value=np.max(array)
min_value=np.min(array)

print("\nMean of the array:",mean_value)
print("\nMax of the array:",max_value)
print("\nMin of the array:",min_value)



Mean of the array: 35.0

Max of the array: 55

Min of the array: 15


In [8]:
zeroes_array=np.zeros(4)
ones_array=np.ones(10)
print("\nArrays of zero",zeroes_array)
print("\nArrays of ones",ones_array)


Arrays of zero [0. 0. 0. 0.]

Arrays of ones [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
array=np.array([2,4,6,8,10])
reshaped_array=np.reshape(array,(5,1))
print("\nReshaped Array:",reshaped_array)


Reshaped Array: [[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]


In [11]:
range_array=np.arange(5,15,2)
print("\nArray with range from 5 to 15 with step 2 :",range_array)


Array with range from 5 to 15 with step 2 : [ 5  7  9 11 13]


In [15]:
identity_matrix=np.identity(3)
print("\nIdentity Matrix :\n",identity_matrix)


Identity Matrix :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
matrix=np.array([[1,2,3],[4,5,6]])

transpose_matrix=np.transpose(matrix)
print("\nOriginal Matrix:\n",matrix)
print("\nTranspose Matrix:\n",transpose_matrix)



Original Matrix:
 [[1 2 3]
 [4 5 6]]

Transpose Matrix:
 [[1 4]
 [2 5]
 [3 6]]


In [19]:
array_3D=np.array([[[1,2,3],[4,5,6],[7,8,9]]
                   ,[[10,11,12],[13,14,15],[16,17,18]]
                   ,[[19,20,21],[22,23,24],[25,26,27]]])
print("\n 3D array :\n")
print(array_3D)


 3D array :

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [20]:
for depth_slice in array_3D:
    print(depth_slice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


In [22]:
#code to accaess selement of 2d array
array_2d=np.array([[10,20,30],[40,50,60]])
elememt=array_2d[1,2]
print("\nIndexed Element ;",elememt)


Indexed Element ; 60


In [23]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
sliced_array=array_2d[1:,1:]
print("Sliced Array:\n",sliced_array)

Sliced Array:
 [[5 6]
 [8 9]]


In [25]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
concatinated_array=np.concatenate((array1, array2))
print("Concatinated Array :",concatinated_array)

Concatinated Array : [1 2 3 4 5 6]


In [26]:
array=np.array([1,2,3,4,5,6])
split_array=np.split(array,3)
print("Splitted arrays:",split_array)

Splitted arrays: [array([1, 2]), array([3, 4]), array([5, 6])]


In [29]:
array=np.array([1,2,34,5,5,6,6])
unique_elements=np.unique(array)
print("Array of unique elements: ",unique_elements)

Array of unique elements:  [ 1  2  5  6 34]


In [30]:
array=np.array([1,2,3,4,5])
reverse_array=np.flip(array)
print("REversed Array:",reverse_array)

REversed Array: [5 4 3 2 1]


In [32]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
stacked_array=np.vstack((array1,array2))
print("Stacked array:\n",stacked_array)

Stacked array:
 [[1 2 3]
 [4 5 6]]


In [33]:
array=np.array([1,2,3])
repeated_array=np.repeat(array,3)
print("Repeated arrays",repeated_array)

Repeated arrays [1 1 1 2 2 2 3 3 3]


In [35]:
array=np.array([1.1,2.2,3.3],dtype=np.float64)
int_array=array.astype(np.int32)
print("Integer Array :",int_array)



Integer Array : [1 2 3]


In [3]:
string_array=np.array(['apple','banana','cherry'])
print("String Array:",string_array)

String Array: ['apple' 'banana' 'cherry']


In [4]:
array=np.array([1,2,3])
tiled_array=np.tile(array,3)
print("Tiled Array :",tiled_array)

Tiled Array : [1 2 3 1 2 3 1 2 3]


In [5]:
random_array=np.random.randint(1,100,size=(3,3))
print("\nRandom Integer Array:\n",random_array)


Random Integer Array:
 [[82  3 78]
 [43 14 87]
 [46 96 25]]


In [6]:
array=np.array([1,0,3,0])
boolean_array=array.astype(bool)
print("Boolean Array :\n",boolean_array)

Boolean Array :
 [ True False  True False]


In [7]:
array=np.array([1,2,3,4,3])
array[array==3]=99
print("Array after replacement :",array)

Array after replacement : [ 1  2 99  4 99]


In [8]:
array=np.array([1,2,3,4,3])
np.random.shuffle(array)
print("Shuffled Array :",array)

Shuffled Array : [3 3 2 4 1]


In [9]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
stacked_array=np.hstack((array1,array2))
print("Horizontally Stacked Arrays :",stacked_array)

Horizontally Stacked Arrays : [1 2 3 4 5 6]


In [10]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
split_rows=np.vsplit(array_2d,3)
print(split_rows)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [11]:
array=np.array([10,20,30,40,50])
bool_index=array>30
print(bool_index)
filtered_array=array[bool_index]
print("Filtered array : \n",filtered_array)

[False False False  True  True]
Filtered array : 
 [40 50]


In [12]:
list_of_strings=[['cat','dog'],['apple','banana']]
string_array=np.array(list_of_strings)
print("string array :\n",string_array)

string array :
 [['cat' 'dog']
 ['apple' 'banana']]


In [13]:
employee_data=np.array([[101,'Alice',28,'HR'],[102,'Bob',34,'Finance'],[103,'Charlie',25,'IT'],[104,'David',30,'Marketing'],[105,'Eve',29,'It']])
print("Employee Data Array :\n",employee_data)

Employee Data Array :
 [['101' 'Alice' '28' 'HR']
 ['102' 'Bob' '34' 'Finance']
 ['103' 'Charlie' '25' 'IT']
 ['104' 'David' '30' 'Marketing']
 ['105' 'Eve' '29' 'It']]


In [14]:
date_array=np.arange('2024-01-01','2024-01-11',dtype='datetime64[D]')
print("Date Array :",date_array)

Date Array : ['2024-01-01' '2024-01-02' '2024-01-03' '2024-01-04' '2024-01-05'
 '2024-01-06' '2024-01-07' '2024-01-08' '2024-01-09' '2024-01-10']


In [15]:
data=np.array([(1,'Alice'),(2,'Bob')],dtype=[('ID','i4'),('Name','U10')])
print("Structured Data",data)

Structured Data [(1, 'Alice') (2, 'Bob')]


In [16]:
array_2d=np.array([[1,2,3],[4,5,6]])
swapped_array=np.swapaxes(array_2d,0,1)
print("Swapped Axes Array :\n",swapped_array)

Swapped Axes Array :
 [[1 4]
 [2 5]
 [3 6]]


In [21]:
employee_data_type=np.dtype([('EmployeeId','i4'),('Name','U50'),('Department','U30'),('Salary','f8')])
#i4 for 4bit integer 
#string of max kength 50
#string of max length 30
# 8byte float

employees=np.array([(101,'John Doe','HR',55000.50),(102,'Jane Smith','IT',72000.75),(103,'Emily Davis','Finance',61000.00),(104,'MIchael Johnson','Marketing',59000.74)],dtype=employee_data_type)
print("Employee Data :")
print(employees)

#acessing specific fields
print("]nNames of Employees")
print(employees['Name'])

print("\nSalaries of employees:")
print(employees['Salary'])


Employee Data :
[(101, 'John Doe', 'HR', 55000.5 ) (102, 'Jane Smith', 'IT', 72000.75)
 (103, 'Emily Davis', 'Finance', 61000.  )
 (104, 'MIchael Johnson', 'Marketing', 59000.74)]
]nNames of Employees
['John Doe' 'Jane Smith' 'Emily Davis' 'MIchael Johnson']

Salaries of employees:
[55000.5  72000.75 61000.   59000.74]


In [22]:
#define structured array with addiotional fields
employee_data_type=np.dtype([('EmployeeId','i4'),
                             ('Name','U50'),
                             ('Department','U30'),
                             ('Salary','f8'),
                             ('PerformanceRating','f4'),
                             ('Bonus','f8')])
#i4 for 4bit integer 
#string of max kength 50
#string of max length 30
# 8byte float
#8byte float initialy set to zero

#create the array with employee dat including performance
employees=np.array([(101,'John Doe','HR',55000.50,4.5,0.0),
                    (102,'Jane Smith','IT',72000.75,4.8,0.0),
                    (103,'Emily Davis','Finance',61000.00,3.9,0.0),
                    (104,'MIchael Johnson','Marketing',59000.74,4.2,0.0),
                    (105,'Anna White','sales',67000.00,4.7,0.0)],dtype=employee_data_type)
print(" INitialEmployee Data :")
print(employees)


#calculate bonus based on dept and performance



 INitialEmployee Data :
[(101, 'John Doe', 'HR', 55000.5 , 4.5, 0.)
 (102, 'Jane Smith', 'IT', 72000.75, 4.8, 0.)
 (103, 'Emily Davis', 'Finance', 61000.  , 3.9, 0.)
 (104, 'MIchael Johnson', 'Marketing', 59000.74, 4.2, 0.)
 (105, 'Anna White', 'sales', 67000.  , 4.7, 0.)]
