In [24]:
#finding smallest no in an array
import numpy as np
a=np.random.rand(5)
z=np.array(a)
print(z)
small=z[0]
for i in z:
    if(i<small):
        small=i
print("smallest",small)

[0.03951569 0.40726748 0.81389874 0.96999585 0.59439596]
smallest 0.03951568879576128


In [25]:
#find the largest no in an array
a=np.random.rand(5)
z=np.array(a)
print(z)
max=z[0]
for i in z:
    if i>max:
        max=i
print("Largest",max)


[0.52485145 0.2516967  0.62340659 0.09902545 0.75928971]
Largest 0.7592897061938653


In [26]:
#find the second smallest element in an array
a=np.random.rand(5)
print(a)
if a[0]<a[1]:
   smallest,second_smallest=a[0],a[1]
else:
   smallest,second_smallest=a[1],a[0]
for i in a[2:]:
    if i<smallest:
      second_smallest=smallest
      smallest=i
    elif smallest < i < second_smallest:
        second_smallest = i


            
print("second_smallest:",second_smallest)





[0.38806703 0.56369798 0.77157889 0.43369416 0.19039727]
second_smallest: 0.3880670260585647


In [27]:
#finding second_largest in an array
z=np.random.rand(5)
print(z)

if z[0]<z[1]:
    largest,second_largest=z[1],z[0]
else:
    largest,second_largest=z[0],z[1]

for i in z[2:]:
    if i>largest:
        second_largest=largest
        largest=i
    elif largest >i>second_largest:
           second_largest=i

print("Largest element:", largest)
print("Second largest element:", second_largest)


        



[0.33696765 0.72442241 0.86640979 0.28850161 0.39169906]
Largest element: 0.8664097923907248
Second largest element: 0.724422414673539


In [28]:

import numpy as np

a = np.random.rand(5)
print("Original Array:", a)

n = len(a)
for i in range(n):
    for j in range(0, n-i-1):
        if a[j] > a[j+1]:
            
            a[j], a[j+1] = a[j+1], a[j]

print("Sorted Array:", a)


Original Array: [0.77101109 0.36036055 0.15984668 0.7857865  0.53322808]
Sorted Array: [0.15984668 0.36036055 0.53322808 0.77101109 0.7857865 ]


In [29]:
#count the frequency of each element

a = ["ab","ab","ok","ok","ok","js","ok"]
c = {}

for i in a:
    if i in c:
        c[i] += 1  
    else:
        c[i] = 1 

print(c)




{'ab': 2, 'ok': 4, 'js': 1}


In [30]:
#rearrange the array in increasing Or decreasing order
a=[5,1,8,9,0,3,2]
n=len(a)
for i in range(n):
    for j in range(0,n-i-1):
      if(a[j]>a[j+1]): #for decreasing use(a[j]<a[j+1])
         a[j],a[j+1]=a[j+1],a[j]

print(a)

[0, 1, 2, 3, 5, 8, 9]


In [31]:
#calculate the sum of elements of an array

a=[1,2,3,7,5,8]
add=0
for i in a:
    add=add+i
print(add)

26


In [32]:
#rotate an array by k elements--block swap algorithm


def rotate_array(arr, k):
    n = len(arr)
    k = k % n 
    return arr[k:] + arr[:k]


a = [1, 2, 3, 4, 4, 6, 8]

n = int(input("Enter the number of elements to rotate by (k): "))

result =rotate_array(a, n)

print("Rotated array:", result)




Rotated array: [4, 4, 6, 8, 1, 2, 3]


In [33]:
#averagre of elem of arrays
a = [1, 2, 3, 4, 4, 6, 8]
add=0

for i in a :
    add=add+i
Average=add/len(a)
print(Average)


4.0


In [ ]:
a = [1, 2, 3, 4, 4, 6, 8]

# Calculate average
average = sum(a) / len(a)

print("Average:", average)


In [36]:
import statistics

a = [1, 2, 3, 4, 4, 6, 8]
median = statistics.median(a)

print("Median:", median)


Median: 4


In [37]:
def find_median(arr):
   
    arr.sort()
    n = len(arr)

   
    if n % 2 == 1:  # Odd number of elements
        median = arr[n // 2]
    else:  # Even number of elements
        median = (arr[(n // 2) - 1] + arr[n // 2]) / 2

    return median


a = [1, 2, 3, 4, 4, 6, 8]

median = find_median(a)

print("Median:", median)


Median: 4


In [4]:
#remove duplicate in sorted
a = [1, 2, 2, 3, 4, 5, 5]
unique_elements = []  

for i in a:
    if len(unique_elements) == 0 or unique_elements[-1] != i:
        unique_elements.append(i)

print(unique_elements)



[1, 2, 3, 4, 5]


In [5]:
#removing duplicate in unsorted
a=[1,2,3,2,4,1,5]
unique_elements=list(set(a))
unique_elements


[1, 2, 3, 4, 5]

In [7]:
#remove duplicate in unsorted
a=[1,2,3,2,4,1,5]

for i in range(len(a)):
    if(a.count(i)>1):
        a.remove(i)

print(a)



[3, 2, 4, 1, 5]


In [15]:
#add an ele in array
a=[1,2,3,4,5]
a.append(6)
print(a)
a.insert(2,10)
print(a)
a.extend([11,20,33])
print(a)



[1, 2, 3, 4, 5, 6]
[1, 2, 10, 3, 4, 5, 6]
[1, 2, 10, 3, 4, 5, 6, 11, 20, 33]


In [16]:
#add a new ele
a = [1, 2, 3, 4, 5]  
new_element = 6  
new_list = []

for i in a:
    new_list.append(i) 

new_list.append(new_element)

print(new_list)  


[1, 2, 3, 4, 5, 6]
